name: gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - production  # Set a branch name to trigger deployment
  pull_request:
    branches:
      - production

jobs:
  deploy-webpack:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Install Dependencies
        run: npm install

      - name: Build for production
        run: gh-pages -d dist --cname code.esporterz.com